const sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);const $=id=>document.getElementById(id);
async function login(){const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)$('loginMsg').textContent=error.message;else init();}
async function logout(){await sb.auth.signOut();location.reload()}
async function init(){const {data:{user}}=await sb.auth.getUser();if(!user){$('login').classList.remove('hidden');$('app').classList.add('hidden');return}const {data:a}=await sb.from('admin_users').select('*').eq('user_id',user.id).single();if(!a){$('loginMsg').textContent='This account is not an authorized temple admin.';await sb.auth.signOut();return}$('login').classList.add('hidden');$('app').classList.remove('hidden');loadAll();}
function showTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}
async function loadAll(){loadEvents();loadNews();loadGallery();loadSettings()}
async function loadEvents(){const {data}=await sb.from('events').select('*').order('event_date');$('eventAdmin').innerHTML=(data||[]).map(x=>`<div class="row"><b>${x.title_te}</b>${x.event_date} — ${x.description_te||''}<br><button onclick="deleteRow('events','${x.id}',loadEvents)">Delete</button></div>`).join('')}
async function addEvent(){const o={title_te:$('etitle').value,description_te:$('edesc').value,event_date:$('edate').value,start_time:$('estart').value||null,end_time:$('eend').value||null,location_te:$('elocation').value};const {error}=await sb.from('events').insert(o);if(error)alert(error.message);else{['etitle','edesc','edate','estart','eend','elocation'].forEach(id=>$(id).value='');loadEvents()}}
async function loadNews(){const {data}=await sb.from('announcements').select('*').order('published_at',{ascending:false});$('newsAdmin').innerHTML=(data||[]).map(x=>`<div class="row"><b>${x.title_te}</b><p>${x.body_te}</p><button onclick="deleteRow('announcements','${x.id}',loadNews)">Delete</button></div>`).join('')}
async function addNews(){const {error}=await sb.from('announcements').insert({title_te:$('ntitle').value,body_te:$('nbody').value,published:true});if(error)alert(error.message);else{$('ntitle').value='';$('nbody').value='';loadNews()}}
async function loadGallery(){const {data}=await sb.from('gallery_photos').select('*').order('sort_order');$('galleryAdmin').innerHTML=(data||[]).map(x=>`<div class="row"><img src="${x.image_url}" style="width:100%;height:170px;object-fit:cover"><b>${x.title_te||''}</b><button onclick="deletePhoto('${x.id}','${x.image_url}')">Delete</button></div>`).join('')}
async function uploadPhoto(){const f=$('photoFile').files[0];if(!f)return alert('Choose a photo');const path=`${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from('temple-gallery').upload(path,f);if(up.error)return alert(up.error.message);const {data}=sb.storage.from('temple-gallery').getPublicUrl(path);const ins=await sb.from('gallery_photos').insert({title_te:$('photoTitle').value,image_url:data.publicUrl,alt_te:$('photoTitle').value,published:true});if(ins.error)alert(ins.error.message);else{$('uploadMsg').textContent='Uploaded successfully';$('photoFile').value='';$('photoTitle').value='';loadGallery()}}
async function deletePhoto(id,url){if(!confirm('Delete this photo?'))return;await deleteRow('gallery_photos',id,loadGallery)}
async function deleteRow(table,id,cb){if(!confirm('Delete this item?'))return;const {error}=await sb.from(table).delete().eq('id',id);if(error)alert(error.message);else cb()}
async function loadSettings(){const {data}=await sb.from('site_settings').select('*').eq('id',1).single();if(data){$('sname').value=data.temple_name_te;$('saddress').value=data.address_te;$('sp1').value=data.phone_1;$('sp2').value=data.phone_2;$('swa').value=data.whatsapp_url;$('sig').value=data.instagram_url;$('smap').value=data.maps_url;$('stag').value=data.hero_tagline_te}}
async function saveSettings(){const o={temple_name_te:$('sname').value,address_te:$('saddress').value,phone_1:$('sp1').value,phone_2:$('sp2').value,whatsapp_url:$('swa').value,instagram_url:$('sig').value,maps_url:$('smap').value,hero_tagline_te:$('stag').value,updated_at:new Date().toISOString()};const {error}=await sb.from('site_settings').update(o).eq('id',1);$('setMsg').textContent=error?error.message:'Saved successfully.'}
init();
